### ISSUE TITLE
10. Context of the simulation

### ISSUE THREAD

**Issue by progmartin** [progmartin/soen-343-team-2--delivery-1#10]
The edit button in the simulation group box opens a form that allows users to perform the following actions:

Place house inhabitants in specific rooms, or outside home
Block windows movement by putting an arbitrary object

7pts

**Comment by DerekRuiz** [comment]
Button to display a new window to edit the context is complete.
Can move non logged in users from location to location.
Can block and unblock windows with an arbitrary object.
