### ISSUE TITLE
11. Smart Home dashboard

### ISSUE THREAD

**Issue by progmartin** [progmartin/soen-343-team-2--delivery-1#11]
Smart home simulator user interface

·         Simulation group completely working including on/off, edit simulation buttons, and links to change current user, location, outside temperature, and date and time

15pts

**Comment by DerekRuiz** [comment]
The following functions have been completed:
- Display the user logged in
- Display the logged in user's location
- Change the user's location
- Display and change outside temperature
- Display date and time

Functions still to be done:
- On/Off simulation
- Edit simulation button

**Comment by progmartin** [comment]
excellent!

**Comment by DerekRuiz** [comment]
Functions added in newest version:
- Clock to increment simulation time
- Turn On/Off the simulation
- Edit simulation context
