### ISSUE TITLE
12. Simulator demo

### ISSUE THREAD

**Issue by progmartin** [progmartin/soen-343-team-2--delivery-1#12]
Record a demo of how to install and execute the simulator and a tour of the functionality that you developed for this delivery 

The video will be divided in two sections.  Follow the steps in the order they are presented.

1. Installation

 - Specify installation requirements with their corresponding versions of JDK, Build system (e.g., Ant, Maven, Graddle, etc)

-  Please specify any external libraries or dependencies used.

 - Explain in a detailed manner how to clone, build and deploy your application

 

2. Simulator Execution & Feature Implementation

 - Provide a clear demonstration of MVC structure using the source code.

 - Provide a clear demonstration of all other Architectural design requirements.

 - Provide clear demonstration of all functional requirements in the grading scheme.

 - Demonstrate the use cases implemented for this delivery with their corresponding unit tests (JUnit)

4pts

**Comment by DerekRuiz** [comment]
Demo Completed
