### ISSUE TITLE
13. Smart home heater (SHH) 22%

### ISSUE THREAD

**Issue by progmartin** [progmartin/soen-343-team-2--delivery-1#59]
Using the observer pattern, the SHH will subscribe to the Smart Home simulator to monitor the presence of individuals in rooms and act accordingly (see details below) .

It will also subscribe to the SHP to determine if the house is in away mode or not.  If the house is in away mode, SHH cannot open any door or window

All commands send from this module to other modules, or to the users will be logged in the corresponding log file, and displayed in the output console

A new SHH tab with the following options

Set zones for heating and cooling.  You can arbitrarily group rooms and home areas in zones.  All rooms in a zone will share the same temperature values
Set desired temperature settings for each zone, for 1 to 3 periods in the day
Read or set the temperature for a specific room.  When a home user sets the temperature, the zone values are overridden for that room. You must indicate it by appending the text “overridden” to the reading of the temperature for any room inside the SHH tab
Set the default temperatures for winter and summer time, when the home is in away mode.  This applies to all zones in a home.  These parameters are set in the SHH tab.

SSH continuous monitoring

SHH l monitors indoor (zones, and overridden rooms)  and outdoor temperature and  it responds to the following events:
If the temperature outside is cooler than inside a zone or room it opens the windows in summer (e.g., June to September).  If windows are blocked by an arbitrary object it notifies the user through the console, and cancels the command.  On away mode SHH shall not open any window for security reasons
 If the temperature inside home is zero degrees, it sends and alert to the users through the console to warn them about potential pipes burst

See Appendix D. Temperature function to understand how the simulation of temperature and the smart heater works.

**Comment by DerekRuiz** [comment]
Issue addressed in pull request #62
